# Generated by Django 4.1.3 on 2022-12-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Circuito",
            fields=[
                ("circuitoid", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(blank=True, max_length=512, null=True)),
                ("criadoem", models.DateField(blank=True, null=True)),
                ("comprimento", models.FloatField(blank=True, null=True)),
                ("curvas", models.IntegerField(blank=True, null=True)),
                ("foto", models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                "db_table": "circuito",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                ("comentarioid", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(blank=True, max_length=80, null=True)),
                ("corpo", models.CharField(blank=True, max_length=2000, null=True)),
                ("criadoem", models.DateField(blank=True, null=True)),
                ("noticia_circuito_circuitoid", models.IntegerField()),
                ("noticia_corrida_ronda", models.IntegerField()),
                ("noticia_construtor_construtorid", models.BigIntegerField()),
                ("noticia_piloto_pilotoid", models.IntegerField()),
            ],
            options={
                "db_table": "comentario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Construtor",
            fields=[
                (
                    "construtorid",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "nacionalidade",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("logo", models.CharField(blank=True, max_length=512, null=True)),
                ("criadoem", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "construtor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Corrida",
            fields=[
                ("ronda", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=512)),
                ("voltas", models.IntegerField(blank=True, null=True)),
                ("temperatura", models.IntegerField(blank=True, null=True)),
                ("temperaturacircuito", models.IntegerField(blank=True, null=True)),
                ("precipitacao", models.IntegerField(blank=True, null=True)),
                ("humidade", models.IntegerField(blank=True, null=True)),
                ("exposicaosolar", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "corrida",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Epoca",
            fields=[
                ("ano", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "epoca",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Equipa",
            fields=[
                ("equipaid", models.BigAutoField(primary_key=True, serialize=False)),
                ("chefe", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "chefetecnico",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("chassis", models.CharField(blank=True, max_length=512, null=True)),
                ("foto_carro", models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                "db_table": "equipa",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Noticia",
            fields=[
                ("noticiaid", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=50)),
                ("corpo", models.CharField(blank=True, max_length=5000, null=True)),
                ("foto", models.CharField(blank=True, max_length=512, null=True)),
                ("criadoem", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "noticia",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Piloto",
            fields=[
                ("pilotoid", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "nacionalidade",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("nascimento", models.DateField(blank=True, null=True)),
                ("foto", models.CharField(blank=True, max_length=512, null=True)),
                ("equipa_construtor_construtorid", models.BigIntegerField()),
            ],
            options={
                "db_table": "piloto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Resultados",
            fields=[
                ("resultadoid", models.AutoField(primary_key=True, serialize=False)),
                ("posinicio", models.IntegerField()),
                ("posfinal", models.IntegerField(blank=True, null=True)),
                ("tempototal", models.IntegerField(blank=True, null=True)),
                ("voltarapida", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "resultados",
                "managed": False,
            },
        ),
    ]
