# Generated by Django 4.1.3 on 2022-12-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "brTalkingformula",
            "0002_authgroup_authgrouppermissions_authpermission_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultadoPontos",
            fields=[
                ("posfinal", models.AutoField(primary_key=True, serialize=False)),
                ("pontos", models.IntegerField()),
            ],
            options={
                "db_table": "resultado_pontos",
            },
        ),
        migrations.AlterModelOptions(
            name="comentario",
            options={"managed": False, "ordering": ["criadoem"]},
        ),
        migrations.AlterModelOptions(
            name="corrida",
            options={"managed": False, "ordering": ["ocorreem"]},
        ),
    ]
