# Generated by Django 4.1.3 on 2022-12-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brTalkingformula", "0003_resultadopontos_alter_comentario_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="noticia",
            options={"managed": False, "ordering": ["-criadoem"]},
        ),
    ]
