# Generated by Django 4.1.3 on 2022-12-30 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Circuito",
            fields=[
                ("circuitoid", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(blank=True, max_length=512, null=True)),
                ("criadoem", models.DateField(blank=True, null=True)),
                ("comprimento", models.FloatField(blank=True, null=True)),
                ("curvas", models.IntegerField(blank=True, null=True)),
                ("foto", models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                "db_table": "circuito",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                ("comentarioid", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=80)),
                ("corpo", models.CharField(max_length=2000)),
                ("criadoem", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "comentario",
                "ordering": ["criadoem"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Construtor",
            fields=[
                (
                    "construtorid",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(blank=True, max_length=512)),
                ("nacionalidade", models.CharField(blank=True, max_length=512)),
                ("logo", models.CharField(blank=True, max_length=512)),
                ("criadoem", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "construtor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Corrida",
            fields=[
                ("ronda", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=512)),
                ("voltas", models.IntegerField(blank=True, null=True)),
                ("ocorreem", models.DateField(blank=True, null=True)),
                ("horas", models.CharField(max_length=512)),
                ("temperatura", models.IntegerField(blank=True, null=True)),
                ("temperaturacircuito", models.IntegerField(blank=True, null=True)),
                ("precipitacao", models.IntegerField(blank=True, null=True)),
                ("humidade", models.IntegerField(blank=True, null=True)),
                ("exposicaosolar", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "corrida",
                "ordering": ["ocorreem"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.SmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Epoca",
            fields=[
                ("ano", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "epoca",
                "ordering": ["-ano"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Equipa",
            fields=[
                ("equipaid", models.BigAutoField(primary_key=True, serialize=False)),
                ("chefe", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "chefetecnico",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("chassis", models.CharField(blank=True, max_length=512, null=True)),
                ("foto_carro", models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                "db_table": "equipa",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Noticia",
            fields=[
                ("noticiaid", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=50)),
                ("corpo", models.CharField(blank=True, max_length=5000, null=True)),
                ("foto", models.CharField(max_length=512)),
                ("criadoem", models.DateField()),
            ],
            options={
                "db_table": "noticia",
                "ordering": ["-criadoem"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Piloto",
            fields=[
                ("pilotoid", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "nacionalidade",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("nascimento", models.DateField(blank=True, null=True)),
                ("foto", models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                "db_table": "piloto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Resultados",
            fields=[
                ("resultadoid", models.AutoField(primary_key=True, serialize=False)),
                ("posinicio", models.IntegerField()),
                ("tempototal", models.IntegerField()),
                ("voltarapida", models.IntegerField()),
            ],
            options={
                "db_table": "resultado",
                "ordering": ["posfinal"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ResultadoPontos",
            fields=[
                ("posfinal", models.AutoField(primary_key=True, serialize=False)),
                ("pontos", models.IntegerField()),
            ],
            options={
                "db_table": "resultado_pontos",
            },
        ),
        migrations.CreateModel(
            name="PilotoEquipa",
            fields=[
                (
                    "piloto_pilotoid",
                    models.OneToOneField(
                        db_column="piloto_pilotoid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="brTalkingformula.piloto",
                    ),
                ),
                ("equipa_construtor_construtorid", models.BigIntegerField()),
            ],
            options={
                "db_table": "piloto_equipa",
                "managed": False,
            },
        ),
    ]
